#!/usr/bin/env sh
#. "${0%/*}/h"

. "$(dirname -- "$0")/_/husky.sh"

echo "PORRAZ";
# Rodar o php stan

./vendor/bin/phpstan
exit 1;

if [ $? -n 0 ]; then
    echo "Opa!!!, Foi mal com PHPSTAN, Arrum e organize o codigo antes de continuar . . . 😉"
    exit 1;
fi

# Formatar cada arquivo alterado usando laraVEL Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")


for FILE in STAGED_FILES

do
  ./vendor/bin/pint "${FILE}"
  git add "${FILE}"

done;